### ISSUE TITLE
Long-running process: clearInterval does not work across separate invocations

### ISSUE THREAD

**Issue by jessefulton** [skpm/sketch-polyfill-setTimeout#2]
I'm trying to create a plugin which can start and stop a long-running process. From what I've read, skpm timers should automatically handle fibers and keeping scripts running in the background. However, when I actually try to implement this, nothing seems to work. I've also tried explicitly adding my own fiber handlers or setting the cocoa script `shouldKeepAround` properties and nothing seems to work.

Below is a simple example of something I would expect to work, but does not (try "starting" and then restarting or stopping the plugin - the interval never clears.)

```
import sketch from 'sketch'

var interval = null;

export function stop(context) {
    console.log("Stopping interval", interval);
    clearInterval(interval);
}

export function start(context) {
    console.log("Starting interval", interval);
    if (interval) { return; }
    interval = setInterval(function() {
        console.log("Inside interval fn", interval);
    }, 2000);
    console.log("Started interval", interval);
}
```

Any help much appreciated!

(I'm on Sketch 51.3 and skpm 1.1.7)

**Comment by mathieudutour** [comment]
So I'm guessing you have 1 command to start and 1 command to stop? Each command has its own javascript context so when you run the `stop` command, `interval` is `null`.

But this should work:
```js
import sketch from 'sketch'

var interval = null;

export function startOrStop(context) {
    if (interval) {
      clearInterval(interval);
      console.log("Stopping interval", interval);
      return;
    }

    console.log("Starting interval", interval);
    interval = setInterval(function() {
        console.log("Inside interval fn", interval);
    }, 2000);
    console.log("Started interval", interval);
}
```

**Comment by jessefulton** [comment]
No luck. This is the console output after calling it twice:

```
Starting interval null
Started interval 0
Inside interval fn 0
Inside interval fn 0
Inside interval fn 0
Inside interval fn 0
Starting interval null
Started interval 0
Inside interval fn 0
Inside interval fn 0
Inside interval fn 0
Inside interval fn 0
Inside interval fn 0
Inside interval fn 0
Inside interval fn 0
```
Note that it prints *"Starting interval null"* twice and continues instead of *"Stopping interval"*

Here are the relevant parts of my `manifest.json`:

```json
{
  "compatibleVersion": 3,
  "bundleVersion": 1,
  "icon": "icon.png",
  "commands": [
    {
      "name": "Toggle",
      "identifier": "toggle-command",
      "script": "./my-command.js",
      "handler": "startOrStop"
    }
  ],
  "menu": {
    "title": "Test App",
    "items": [
      "toggle-command"
    ]
  }
}
```
